##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.19.2] date: [Sun Mar 19 17:24:38 CST 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = led_spl


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/usart.c \
Core/Src/delay.c \
Core/Src/led.c \
Core/Src/main.c \
Drivers/CMSIS/CM3/src/core_cm3.c \
Drivers/STM32F10x_StdPeriph_Driver/src/misc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c \
Core/Src/stm32f10x_it.c \
Core/Src/system_stm32f10x.c  

# ASM sources
ASM_SOURCES =  \
startup/startup_stm32f10x_hd.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-D STM32F10X_HD \
-D USE_STDPERIPH_DRIVER 

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F10x_StdPeriph_Driver/inc \
-IDrivers/CMSIS/CM3/inc \


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103ZETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -specs=nosys.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# flash
#######################################
OCD=openocd
OCD_INTERFACE= -f interface/stlink-v2.cfg 
OCD_TARGET= -f target/stm32f1x.cfg 
FLASH_FILE=$(BUILD_DIR)/$(TARGET).bin
FLASH_ADDR= 0x8000000
OCD_COMMAND = -c init \
 -c halt \
 -c "flash write_image erase $(FLASH_FILE) $(FLASH_ADDR)" \
 -c reset 

flash: all
	$(OCD) $(OCD_INTERFACE) $(OCD_TARGET) $(OCD_COMMAND)


#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***